name: pyspark-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - arrow-cpp=0.14.1=py37hb44d003_4
  - attrs=19.2.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - boost-cpp=1.70.0=hd59e818_1
  - brotli=1.0.7=h6de7cb9_1000
  - bzip2=1.0.8=h01d97ff_1
  - c-ares=1.15.0=h01d97ff_1001
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - double-conversion=3.1.5=h6de7cb9_1
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - gflags=2.2.2=h6de7cb9_1001
  - glib=2.56.2=hd9629dc_0
  - glog=0.4.0=h6de7cb9_1
  - grpc-cpp=1.23.0=h5c95ec2_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9b=he5867d9_2
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.5.0=py_0
  - jupyterlab=1.1.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libevent=2.1.10=h212c5bf_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.8.0=hfbae3c0_0
  - libsodium=1.0.16=h3efe00b_0
  - lz4-c=1.8.3=h6de7cb9_1001
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py37_0
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - openssl=1.1.1d=h1de35cc_2
  - pandas=0.25.1=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parquet-cpp=1.5.1=2
  - parso=0.5.1=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.2.3=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - ptyprocess=0.6.0=py37_0
  - py4j=0.10.7=py37_0
  - pyarrow=0.14.1=py37he1943e6_2
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.15.4=py37h1de35cc_0
  - pyspark=2.4.4=py_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.5.5=py_0
  - re2=2019.09.01=h6de7cb9_0
  - readline=7.0=h1de35cc_5
  - send2trash=1.5.0=py37_0
  - setuptools=41.4.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.12.0=py37_0
  - snappy=1.1.7=h6de7cb9_1002
  - sqlite=3.30.0=ha441bb4_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - thrift-cpp=0.12.0=h874095a_1004
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.3=py37_0
  - uriparser=0.9.3=h6de7cb9_1
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.0=ha9f0a20_0
prefix: /Users/cnuno/anaconda3/envs/pyspark-env

